### ISSUE TITLE
this code version

### ISSUE THREAD

**Issue by yqcs** [BenDerPan/go-wappalyzer#1]
hi，Will you continue to maintain this tool？

**Comment by BenDerPan** [comment]
maybe if I am not busy. if you need any new feature or find any bug, feel free to tell me

**Comment by yqcs** [comment]
According to the fingerprint database to determine what technology the website uses，thanks.

**Comment by BenDerPan** [comment]
it's already work as you say

**Comment by yqcs** [comment]
thanks. However, it is not applicable to the new wapalyzer fingerprint library，looking forward to compatibility with the new version

**Comment by BenDerPan** [comment]
Have you try to update the app.json?

**Comment by yqcs** [comment]
I have a try. Because the existing fingerprint database is not accurate enough. However, the new fingerprint database is not applicable

**Comment by yqcs** [comment]
好兄弟咱们都是中国人啊，我搁着翻译了半天。。。。

**Comment by BenDerPan** [comment]
Hahaha...you know too much
